/* eslint-disable no-console */
// Generate src/version.ts from the first line of README.md
const fs = require('fs');
const path = require('path');

try {
  const repoRoot = process.cwd();
  const readmePath = path.join(repoRoot, 'README.md');
  const outPath = path.join(repoRoot, 'src', 'version.ts');

  const readme = fs.readFileSync(readmePath, 'utf8');
  const firstLine = (readme.split(/\r?\n/, 1)[0] || '').trim();
  // Expect formats like: "# RichYAML v0.1.4" or "# RichYAML v1.0.0-beta"
  const m = firstLine.match(/^#\s*RichYAML\s+(v[0-9]+\.[0-9]+\.[0-9]+(?:[-.a-zA-Z0-9+]*)?)/);
  const version = m ? m[1] : 'v0.0.0';

  const content = `// Auto-generated by scripts/extract-version.js. Do not edit.
export const RICHYAML_VERSION = '${version}';
`;
  fs.writeFileSync(outPath, content);
  console.log(`[version] Generated src/version.ts with ${version}`);
} catch (err) {
  console.error('[version] Failed to extract version:', err);
  // Still write a default file to avoid TS import errors
  try {
    const outPath = path.join(process.cwd(), 'src', 'version.ts');
    fs.writeFileSync(outPath, `export const RICHYAML_VERSION = 'v0.0.0';\n`);
  } catch {}
  process.exit(0);
}
